BEGIN;

CREATE TABLE IF NOT EXISTS clientes (
    id_cliente BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cedula VARCHAR(20) NOT NULL UNIQUE,
    nombres VARCHAR(100) NOT NULL,
    apellidos VARCHAR(100) NOT NULL,
    fecha_nacimiento DATE NOT NULL,
    direccion VARCHAR(200),
    telefono VARCHAR(20),
    correo VARCHAR(150)
);

CREATE TABLE IF NOT EXISTS cuentas (
    id_cuenta BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_cuenta VARCHAR(20) NOT NULL UNIQUE,
    tipo_cuenta VARCHAR(20) NOT NULL
        CHECK (tipo_cuenta IN ('Ahorros', 'Corriente')),
    fecha_apertura DATE NOT NULL DEFAULT CURRENT_DATE,
    saldo_inicial NUMERIC(14, 2) NOT NULL DEFAULT 0
        CHECK (saldo_inicial >= 0),
    estado VARCHAR(20) NOT NULL DEFAULT 'Activa'
        CHECK (estado IN ('Activa', 'Cerrada')),
    id_cliente BIGINT NOT NULL REFERENCES clientes(id_cliente)
);

CREATE TABLE IF NOT EXISTS transacciones (
    id_transaccion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cuenta BIGINT NOT NULL REFERENCES cuentas(id_cuenta),
    tipo VARCHAR(30) NOT NULL CHECK (
        tipo IN (
            'Deposito',
            'Retiro',
            'Transferencia Entrada',
            'Transferencia Salida'
        )
    ),
    monto NUMERIC(14, 2) NOT NULL CHECK (monto > 0),
    fecha DATE NOT NULL DEFAULT CURRENT_DATE,
    descripcion VARCHAR(255),
    id_cuenta_destino BIGINT REFERENCES cuentas(id_cuenta)
);

CREATE TABLE IF NOT EXISTS prestamos (
    id_prestamo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente BIGINT NOT NULL REFERENCES clientes(id_cliente),
    monto NUMERIC(14, 2) NOT NULL CHECK (monto > 0),
    interes NUMERIC(7, 2) NOT NULL CHECK (interes >= 0),
    plazo INTEGER NOT NULL CHECK (plazo > 0),
    estado VARCHAR(20) NOT NULL DEFAULT 'Pendiente'
        CHECK (estado IN ('Pendiente', 'Aprobado', 'Rechazado'))
);

CREATE TABLE IF NOT EXISTS usuarios (
    id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario VARCHAR(50) NOT NULL UNIQUE,
    contrasena VARCHAR(255) NOT NULL,
    rol VARCHAR(50) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_cuentas_cliente
    ON cuentas(id_cliente);
CREATE INDEX IF NOT EXISTS idx_transacciones_cuenta_fecha
    ON transacciones(id_cuenta, fecha DESC, id_transaccion DESC);
CREATE INDEX IF NOT EXISTS idx_prestamos_cliente
    ON prestamos(id_cliente);

COMMIT;
